/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Threat Actors are actual individuals, groups, or organizations believed to be operating with malicious intent.
 */
export type ThreatActor = Core & {
  /**
   * The type of this object, which MUST be the literal `threat-actor`.
   */
  type: "threat-actor";
  id?: Id;
  /**
   * This field specifies the type of threat actor. Open Vocab - threat-actor-type-ov
   */
  threat_actor_types?: string[];
  /**
   * A name used to identify this Threat Actor or Threat Actor group.
   */
  name?: string;
  /**
   * A description that provides more details and context about the Threat Actor.
   */
  description?: string;
  /**
   * A list of other names that this Threat Actor is believed to use.
   */
  aliases?: string[];
  /**
   * This is a list of roles the Threat Actor plays. Open Vocab - threat-actor-role-ov
   */
  roles?: string[];
  /**
   * The high level goals of this Threat Actor, namely, what are they trying to do.
   */
  goals?: string[];
  first_seen?: ThreatActorFirstSeen;
  last_seen?: ThreatActorLastSeen;
  /**
   * The skill, specific knowledge, special training, or expertise a Threat Actor must have to perform the attack. Open Vocab - threat-actor-sophistication-ov
   */
  sophistication?: string;
  /**
   * This defines the organizational level at which this Threat Actor typically works. Open Vocab - attack-resource-level-ov
   */
  resource_level?: string;
  /**
   * The primary reason, motivation, or purpose behind this Threat Actor. Open Vocab - attack-motivation-ov
   */
  primary_motivation?: string;
  /**
   * The secondary reasons, motivations, or purposes behind this Threat Actor. Open Vocab - attack-motivation-ov
   */
  secondary_motivations?: string[];
  /**
   * The personal reasons, motivations, or purposes of the Threat Actor regardless of organizational goals. Open Vocab - attack-motivation-ov
   */
  personal_motivations?: string[];
  [k: string]: unknown;
};
/**
 * Common properties and behavior across all STIX Domain Objects and STIX Relationship Objects.
 */
export type Core = Properties;
/**
 * The ​binary data type represents a sequence of bytes. In order to allow pattern matching on custom objects, for all properties that use the binary type, the property name MUST end with '_bin'. The JSON MTI serialization represents this as a base64-­encoded string as specified in RFC4648​. Other serializations SHOULD use a native binary type, if available.
 *
 * This interface was referenced by `Properties`'s JSON-Schema definition
 * via the `patternProperty` "^[a-z][a-z0-9_]{0,245}_bin$".
 */
export type Binary = string;
/**
 * The hex data type encodes an array of octets (8-bit bytes) as hexadecimal. The string MUST consist of an even number of hexadecimal characters, which are the digits '0' through '9' and the letters 'a' through 'f'.  In order to allow pattern matching on custom objects, all properties that use the hex type, the property name MUST end with '_hex'.
 *
 * This interface was referenced by `Properties`'s JSON-Schema definition
 * via the `patternProperty` "^[a-z][a-z0-9_]{0,245}_hex$".
 */
export type Hex = string;
/**
 * The time that this Threat Actor was first seen.
 */
export type ThreatActorFirstSeen = string;
/**
 * The time that this Threat Actor was last seen.
 */
export type ThreatActorLastSeen = string;

/**
 * Rules for custom properties
 */
export interface Properties {}
export interface Id {
  [k: string]: unknown;
}
